// One screenshot per Storybook story (or per page in pages.json), per project.
// Generated by the screenshots-testing skill; adjust MASK and ROOT, keep the rest.
import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';

const STATIC_DIR = process.env.VISUAL_STORYBOOK_DIR ?? 'storybook-static';
const PAGES_FILE = path.join(__dirname, 'pages.json');
// Stories tagged with this are never shot (list them under Caveats).
const SKIP_TAG = 'no-visual';
// Regions that legitimately differ run to run (live maps, third-party embeds).
const MASK: string[] = ['[data-visual-mask]'];
// Fixed "now" for Date, and the seed for Math.random.
const FROZEN_TIME = new Date('2024-01-15T10:00:00Z');
const SEED = 42;

type Target = { id: string; title: string; name: string; url: string; importPath?: string };

function storyTargets(): Target[] {
  const file = ['index.json', 'stories.json'].map((f) => path.join(STATIC_DIR, f)).find((f) => fs.existsSync(f));
  if (!file) return [];
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  const entries: any[] = Object.values(data.entries ?? data.stories ?? {});
  return entries
    .filter((e) => (e.type ?? 'story') === 'story' && !(e.tags ?? []).includes(SKIP_TAG))
    .map((e) => ({
      id: e.id,
      title: e.title ?? e.kind,
      name: e.name,
      importPath: e.importPath,
      url: `/iframe.html?id=${encodeURIComponent(e.id)}&viewMode=story`,
    }));
}

function pageTargets(): Target[] {
  if (!fs.existsSync(PAGES_FILE)) return [];
  const pages: { name: string; path: string }[] = JSON.parse(fs.readFileSync(PAGES_FILE, 'utf8'));
  return pages.map((p) => ({
    id: 'page-' + p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    title: 'Pages',
    name: p.name,
    url: p.path,
  }));
}

// VISUAL_ONLY_FILE: output of changed-stories.sh — story importPaths, or ALL.
function only(targets: Target[]): Target[] {
  const file = process.env.VISUAL_ONLY_FILE;
  if (!file) return targets;
  const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  if (lines.includes('ALL')) return targets;
  const keep = new Set(lines.map((l) => (l.startsWith('./') ? l : './' + l)));
  return targets.filter((t) => t.importPath && keep.has(t.importPath));
}

async function settle(page: Page) {
  await page.waitForLoadState('networkidle');
  await page.evaluate(async () => {
    await document.fonts.ready;
    await Promise.all(
      Array.from(document.images)
        .filter((img) => !img.complete)
        .map((img) => new Promise((r) => { img.onload = img.onerror = r; })),
    );
  });
}

const targets = only([...storyTargets(), ...pageTargets()]);

if (targets.length === 0) {
  test('visual: nothing to shoot', () => {
    test.skip(true, `no stories in ${STATIC_DIR}, no pages.json, or VISUAL_ONLY_FILE matched none`);
  });
}

for (const t of targets) {
  test(`${t.title} / ${t.name} [${t.id}]`, async ({ page }, info) => {
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(e.message));
    page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });

    await page.clock.setFixedTime(FROZEN_TIME);
    await page.addInitScript((seed) => {
      let s = seed >>> 0;
      Math.random = () => {
        s = (s + 0x6d2b79f5) >>> 0;
        let r = Math.imul(s ^ (s >>> 15), 1 | s);
        r = (r + Math.imul(r ^ (r >>> 7), 61 | r)) ^ r;
        return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
      };
    }, SEED);

    const globals = info.project.metadata?.globals;
    await page.goto(globals && t.importPath ? `${t.url}&globals=${globals}` : t.url);
    await settle(page);

    // Storybook shows its error overlay instead of the story when rendering throws.
    const broken = await page.locator('body.sb-show-errordisplay').count();
    expect(broken, `story threw while rendering: ${errors.join(' | ')}`).toBe(0);
    if (errors.length) info.annotations.push({ type: 'console-error', description: errors.join(' | ') });

    // toHaveScreenshot waits for two identical frames before comparing.
    await expect(page).toHaveScreenshot([...t.title.split('/'), `${t.name}.png`], {
      fullPage: true,
      mask: MASK.map((sel) => page.locator(sel)),
    });
  });
}
