#!/usr/bin/env bash
# Initialises the project memory tree at .tlk/memory/.
#
# Layout (see talaka/templates/memory/SCHEMA.md):
#   .tlk/MEMORY.md              # L4 root summary
#   .tlk/SESSION-STATE.md       # L1 hot state
#   .tlk/memory/SCHEMA.md       # ontology
#   .tlk/memory/preferences.md  # L3
#   .tlk/memory/system.md       # L3
#   .tlk/memory/projects.md     # L3
#   .tlk/memory/decisions.md    # L3
#   .tlk/memory/<YYYY-MM-DD>.md # L2 (today's)
#   .tlk/memory/index.jsonl     # L5 (created by memory/tools/search.sh)
#
# Override the artefacts directory with $ARTEFACTS_DIR (e.g. for legacy
# .artefacts/ checkouts that have not migrated yet).
#
# Usage:
#   talaka/memory/tools/init.sh                  # safe init (skips existing files)
#   talaka/memory/tools/init.sh --force          # overwrite stubs from templates
#
# Run from project root.

set -euo pipefail

KIT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TPL_DIR="$KIT_DIR/templates/memory"
ARTEFACTS="${ARTEFACTS_DIR:-.tlk}"
MEM_DIR="$ARTEFACTS/memory"

FORCE=false
for _arg in "$@"; do
  case "$_arg" in
    --force) FORCE=true ;;
    -h|--help) sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  esac
done

mkdir -p "$ARTEFACTS" "$MEM_DIR"

copy_stub() {
  local src="$1" dst="$2"
  if [ -f "$dst" ] && ! $FORCE; then
    echo "  skip $dst (exists)"
    return
  fi
  cp "$src" "$dst"
  echo "  init $dst"
}

# L3 templates
for f in SCHEMA.md preferences.md system.md projects.md decisions.md; do
  copy_stub "$TPL_DIR/$f" "$MEM_DIR/$f"
done

# L1 SESSION-STATE.md
SESSION_STATE="$ARTEFACTS/SESSION-STATE.md"
if [ ! -f "$SESSION_STATE" ] || $FORCE; then
  cat > "$SESSION_STATE" <<'EOF'
# Session State (L1 — Hot)

_Updated by every agent on entry/exit. Pruned by `memory/tools/rollover.sh` when stale (>24h)._

## Active feature
_(none — set by requirements-eliciting or whoever starts the next feature)_

## Active agent
_(none)_

## In-flight decisions
_(append short bullets here as decisions are made; promoted to daily L2 by Zlydni)_

EOF
  echo "  init $SESSION_STATE"
else
  echo "  skip $SESSION_STATE (exists)"
fi

# L2 today's daily file
TODAY="$(date +%Y-%m-%d)"
DAILY="$MEM_DIR/$TODAY.md"
if [ ! -f "$DAILY" ]; then
  cat > "$DAILY" <<EOF
# Daily memory — $TODAY (L2)

_Append-only log. Rolled into L3 by \`memory/tools/promote.sh\` (2-strike rule)._

## Observations
EOF
  echo "  init $DAILY"
else
  echo "  skip $DAILY (exists)"
fi

# L4 root summary
ROOT="$ARTEFACTS/MEMORY.md"
if [ ! -f "$ROOT" ] || $FORCE; then
  cat > "$ROOT" <<'EOF'
# Memory Index (L4)

_Generated by `memory/tools/promote.sh`. Do not hand-edit — edit the linked layer files instead._

## How to use this file
- This is the **first** file every skill should read before starting a task.
- Drill into L3 only when more detail is needed (`memory/preferences.md`, `memory/system.md`, `memory/projects.md`, `memory/decisions.md`).
- Run `bash talaka/memory/tools/search.sh "<query>"` for full-text + ranked retrieval across all layers.

## High-confidence preferences
_(empty — populate by running the pipeline; entries promote here after the 2-strike rule)_

## High-confidence system facts
_(empty)_

## Most-referenced decisions (last 90 days)
_(empty)_

## Recent supersessions
_(empty)_
EOF
  echo "  init $ROOT"
else
  echo "  skip $ROOT (exists)"
fi

echo
echo "Memory tree initialised at $MEM_DIR"
echo "Next: run a feature; Zlydni will append to $DAILY automatically."
echo "      Run \`bash talaka/memory/tools/search.sh '<query>'\` to query across layers."
